[package]
name = "weapon-parser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde-xml-rs = "0.5.1"
serde = { version = "1.0", features = ["derive"] }
chrono = "0.4"
csv = "1.1"
encoding_rs = "0.8.30"